# Generated by Django 3.2 on 2025-05-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
